services:
  # Web Application
  - type: web
    name: prestoliv
    env: node
    rootDir: web
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - fromEnvFile:
          key: NEXT_PUBLIC_SUPABASE_URL
          path: ./.env
      - fromEnvFile:
          key: NEXT_PUBLIC_SUPABASE_ANON_KEY
          path: ./.env
